<a href="https://colab.research.google.com/github/aditi-chauhan16/python-code/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:


!pip install numpy
import numpy as np
t1=(5,6,0,4)
t2=(4,7,8,9)
arr=np.array(t1)
arr2=np.array(t2)

print(arr)
print(arr2)

import pandas as pd
import numpy as np
t1=(5,6,0,4)
t2=(4,7,8,9)
arr=np.array(t1)
arr2=np.array(t2)
arr3=np.arange(2,18).reshape(4,4) #TO CREATE 1D ARRAY
print(arr)
print(arr2)
print(arr3)


import pandas as pd
import numpy as np
pf=pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=["Row1", "Row2","Row3", "Row4","Row5"  ],
                                                   columns=["column1","column2","column3", "column4"])
print(pf)
pf.describe()
pf.info()

import pandas as pd
import numpy as np
pd=pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=["Row1", "Row2","Row3", "Row4","Row5"  ],
                                                   columns=["column1","column2","column3", "column4"])
print(pd)
pd.describe()
pd.info()



[5 6 0 4]
[4 7 8 9]
[5 6 0 4]
[4 7 8 9]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]
      column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19
<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   column1  5 non-null      int64
 1   column2  5 non-null      int64
 2   column3  5 non-null      int64
 3   column4  5 non-null      int64
dtypes: int64(4)
memory usage: 200.0+ bytes
      column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19
<class 'pandas.core.frame.DataFrame'>
Index: 5