<a href="https://colab.research.google.com/github/aditi-chauhan16/python-code/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy
!pip install pandas
import numpy as np
import pandas as pd
l1=[1,2,3,4,5]
t2=(6,7,8,9,10)
a1=np.array(l1)
print(a1)

[1 2 3 4 5]


In [ ]:
print(type(a1))

<class 'numpy.ndarray'>


In [ ]:
a1[2:3]

array([3])

In [ ]:
a2=np.arange(0,20).reshape(5,4)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [ ]:
print(type(a2))

<class 'numpy.ndarray'>


In [ ]:
l2=[0,0,0,0,0]
a3=np.array([l1,l2])
print(a3)

[[1 2 3 4 5]
 [0 0 0 0 0]]


In [ ]:
a4=np.arange(0,20,2).reshape(2,5)
print(a4)

[[ 0  2  4  6  8]
 [10 12 14 16 18]]


In [ ]:
a5=np.random.randint(0,100,20) #random values till 20
print(a5)

[74 17 30 52 99 95 62 43 15 94 33 88 58 56 61 86 94  5  6 75]


In [ ]:
a6=np.arange(0,100).reshape(10,10)
print(a6)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [ ]:
a6[5:6,3:8] #FIRST PAIR IS ROW,SECOND IS COLUMNS

array([[53, 54, 55, 56, 57]])

In [ ]:
a6[::-1]#reverse the row only

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [ ]:
a6[9:,9:]

array([[99]])

In [ ]:
df=pd.DataFrame(data=np.arange(0,2))

In [ ]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [ ]:
df.head()

0
0  0
1  1

In [ ]:
df.tail

<bound method NDFrame.tail of    0
0  0
1  1>

In [ ]:
df.describe

<bound method NDFrame.describe of    0
0  0
1  1>

In [ ]:
!ls

sample_data


In [ ]:
import seaborn as sns #SEABORN IS A LIBRARY IN PYTHON TO DECORATE DATASETS
